# Generated by Django 2.1.5 on 2019-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('Rohini', 'Rohini'), ('CIT', 'CIT'), ('Arunachala', 'Arunachala')], default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('qualification', models.CharField(choices=[('BE', 'BE'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA')], default='', max_length=20)),
                ('specialization', models.CharField(choices=[('computer science', 'computer science'), ('electrical', 'electrical'), ('mechanical', 'mechanical')], default='', max_length=20)),
                ('arrears', models.IntegerField(default='')),
                ('area_of_interest', models.CharField(default='', max_length=25)),
                ('contact', models.CharField(default='', max_length=20)),
                ('address', models.TextField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='', max_length=3)),
                ('month', models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], default='', max_length=20)),
                ('year', models.CharField(choices=[('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010')], default='', max_length=20)),
                ('photo', models.ImageField(default='', upload_to='volt/proof/')),
                ('proof', models.FileField(default='', upload_to='volt/photos/')),
                ('user', models.CharField(default='', max_length=25)),
                ('passid', models.CharField(default='', max_length=20)),
                ('confirm_passid', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('domain', models.CharField(default='', max_length=40)),
                ('position', models.CharField(choices=[('HR_manager', 'HR_manager'), ('Technical_manager', 'Technical_manager'), ('Executive_manager', 'Executive_manager')], default='', max_length=40)),
                ('notice', models.CharField(default='', max_length=40)),
                ('last_ctc', models.IntegerField(default='')),
                ('expext_ctc', models.IntegerField(default='')),
                ('reason', models.CharField(choices=[('HR_manager', 'HR_manager'), ('Technical_manager', 'Technical_manager'), ('Executive_manager', 'Executive_manager')], default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('location', models.CharField(choices=[('cennai', 'chennai'), ('coimbatore', 'coimbatore'), ('bangalore', 'bangalore')], default='', max_length=20)),
                ('experience', models.CharField(choices=[('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year'), ('4 year above', '4 year above')], default='', max_length=20)),
                ('skill', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('PHP', 'PHP')], default='', max_length=20)),
                ('qualification', models.CharField(choices=[('BE', 'BE'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA')], default='', max_length=20)),
                ('user', models.CharField(default='', max_length=25)),
                ('passid', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='forget_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=220)),
                ('passid', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fresher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('degree', models.CharField(choices=[('BE', 'BE'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA')], default='', max_length=20)),
                ('year_of_pass', models.IntegerField(default='')),
                ('skill', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('PHP', 'PHP')], default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('present_address', models.TextField(default='', max_length=20)),
                ('permenant_address', models.TextField(default='', max_length=20)),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='', max_length=3)),
                ('month', models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], default='', max_length=20)),
                ('year', models.CharField(choices=[('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010')], default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=220)),
                ('passid', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
