# Generated by Django 2.1.5 on 2019-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default='')),
            ],
        ),
    ]
